a=input('enter your birth month: ')
b=input('enter your birth month: ')
c=input('enter your birth month: ')
d=input('enter your birth month: ')
e=input('enter your birth month: ')
print(a,b,c,d,e)